	
stages:
    - build
    - deploy
build:
    stage: build
    image: node:12-buster
    tags: &b_runner 
        - builder
        - docker-executor
    script:
        - yarn install
        - yarn build:dev
    artifacts:
        expire_in: 1 week
        paths:
            - build
deploy_develop:
    stage: deploy
    tags: 
      - shell
      - dev
      - deploy-runner
    script:
        - rsync -a ./build/* /var/www/swap-interface/dev
